# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kvisouth <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/01 18:24:16 by kvisouth          #+#    #+#              #
#    Updated: 2022/10/01 18:31:21 by kvisouth         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-02
SRC =  main.c read_number.c convertEN.c ft_is_nbr.c ft_strcat.c ft_ft.c ft_next_line.c ft_strlen.c ft_get_nbr.c ft_putstr.c

all : $(NAME)
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

fclean :
	rm -rf $(NAME)

re: fclean all
